### ISSUE TITLE
No longer a Pypi package!!!??

### ISSUE THREAD

**Issue by thom8047** [fchorney/RPiLiquidCrystal#2]
I haven't ever wanted to publish my personal code as a package to be installed by others, so I have no idea about the process, but can I ask what happened and why you didn't continue the project?

**Comment by fchorney** [comment]
Hi! I don't think I had ever made this a pypi package and I didn't think it was necessarily "done" per se. I haven't hacked on a screen since I initially made this, so I haven't had the need to update or use it. You are free to fork it and publish it yourself as I currently will not have the time to make all the necessary changes. (such as updating to python 3, or making it a proper package, etc) 

Thanks for the interest!

**Comment by thom8047** [comment]
I appreciate the response, and I might!
